version: "3.8"

services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - C:/AI/ComfyUI/output:/comfy-output
      - ./data:/data
      - ./doc:/doc
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - TYPHOON_OCR_API_KEY=0arzXoosKQJUmzahAVNFwTcRdewrCftgRPaWKgOKANyswtod
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    user: "1000:1000"  # เพิ่ม user mapping เพื่อให้ permission ถูกต้อง

volumes:
  n8n_data: